// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FingerprintProtocol.proto

package org.whispersystems.libsignal.fingerprint;

public final class FingerprintProtos {
  private FingerprintProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FingerprintDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes publicKey = 1;
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    boolean hasPublicKey();
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    // optional bytes identifier = 2;
    /**
     * <code>optional bytes identifier = 2;</code>
     */
    boolean hasIdentifier();
    /**
     * <code>optional bytes identifier = 2;</code>
     */
    com.google.protobuf.ByteString getIdentifier();
  }
  /**
   * Protobuf type {@code textsecure.FingerprintData}
   */
  public static final class FingerprintData extends
      com.google.protobuf.GeneratedMessage
      implements FingerprintDataOrBuilder {
    // Use FingerprintData.newBuilder() to construct.
    private FingerprintData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FingerprintData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FingerprintData defaultInstance;
    public static FingerprintData getDefaultInstance() {
      return defaultInstance;
    }

    public FingerprintData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FingerprintData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              publicKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              identifier_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_FingerprintData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_FingerprintData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.class, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder.class);
    }

    public static com.google.protobuf.Parser<FingerprintData> PARSER =
        new com.google.protobuf.AbstractParser<FingerprintData>() {
      public FingerprintData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FingerprintData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FingerprintData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes publicKey = 1;
    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    // optional bytes identifier = 2;
    public static final int IDENTIFIER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString identifier_;
    /**
     * <code>optional bytes identifier = 2;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes identifier = 2;</code>
     */
    public com.google.protobuf.ByteString getIdentifier() {
      return identifier_;
    }

    private void initFields() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      identifier_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, publicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, identifier_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, identifier_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code textsecure.FingerprintData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_FingerprintData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_FingerprintData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.class, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder.class);
      }

      // Construct using org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        identifier_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_FingerprintData_descriptor;
      }

      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getDefaultInstanceForType() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
      }

      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData build() {
        org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData buildPartial() {
        org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData result = new org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identifier_ = identifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData) {
          return mergeFrom((org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData other) {
        if (other == org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance()) return this;
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasIdentifier()) {
          setIdentifier(other.getIdentifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes publicKey = 1;
      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      // optional bytes identifier = 2;
      private com.google.protobuf.ByteString identifier_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identifier = 2;</code>
       */
      public boolean hasIdentifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes identifier = 2;</code>
       */
      public com.google.protobuf.ByteString getIdentifier() {
        return identifier_;
      }
      /**
       * <code>optional bytes identifier = 2;</code>
       */
      public Builder setIdentifier(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identifier = 2;</code>
       */
      public Builder clearIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        identifier_ = getDefaultInstance().getIdentifier();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:textsecure.FingerprintData)
    }

    static {
      defaultInstance = new FingerprintData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:textsecure.FingerprintData)
  }

  public interface CombinedFingerprintOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 version = 1;
    /**
     * <code>optional uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional uint32 version = 1;</code>
     */
    int getVersion();

    // optional .textsecure.FingerprintData localFingerprint = 2;
    /**
     * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
     */
    boolean hasLocalFingerprint();
    /**
     * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
     */
    org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getLocalFingerprint();
    /**
     * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
     */
    org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder getLocalFingerprintOrBuilder();

    // optional .textsecure.FingerprintData remoteFingerprint = 3;
    /**
     * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
     */
    boolean hasRemoteFingerprint();
    /**
     * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
     */
    org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getRemoteFingerprint();
    /**
     * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
     */
    org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder getRemoteFingerprintOrBuilder();
  }
  /**
   * Protobuf type {@code textsecure.CombinedFingerprint}
   */
  public static final class CombinedFingerprint extends
      com.google.protobuf.GeneratedMessage
      implements CombinedFingerprintOrBuilder {
    // Use CombinedFingerprint.newBuilder() to construct.
    private CombinedFingerprint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CombinedFingerprint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CombinedFingerprint defaultInstance;
    public static CombinedFingerprint getDefaultInstance() {
      return defaultInstance;
    }

    public CombinedFingerprint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CombinedFingerprint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 18: {
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = localFingerprint_.toBuilder();
              }
              localFingerprint_ = input.readMessage(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(localFingerprint_);
                localFingerprint_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = remoteFingerprint_.toBuilder();
              }
              remoteFingerprint_ = input.readMessage(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(remoteFingerprint_);
                remoteFingerprint_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_CombinedFingerprint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_CombinedFingerprint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.class, org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.Builder.class);
    }

    public static com.google.protobuf.Parser<CombinedFingerprint> PARSER =
        new com.google.protobuf.AbstractParser<CombinedFingerprint>() {
      public CombinedFingerprint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CombinedFingerprint(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CombinedFingerprint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // optional .textsecure.FingerprintData localFingerprint = 2;
    public static final int LOCALFINGERPRINT_FIELD_NUMBER = 2;
    private org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData localFingerprint_;
    /**
     * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
     */
    public boolean hasLocalFingerprint() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
     */
    public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getLocalFingerprint() {
      return localFingerprint_;
    }
    /**
     * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
     */
    public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder getLocalFingerprintOrBuilder() {
      return localFingerprint_;
    }

    // optional .textsecure.FingerprintData remoteFingerprint = 3;
    public static final int REMOTEFINGERPRINT_FIELD_NUMBER = 3;
    private org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData remoteFingerprint_;
    /**
     * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
     */
    public boolean hasRemoteFingerprint() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
     */
    public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getRemoteFingerprint() {
      return remoteFingerprint_;
    }
    /**
     * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
     */
    public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder getRemoteFingerprintOrBuilder() {
      return remoteFingerprint_;
    }

    private void initFields() {
      version_ = 0;
      localFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
      remoteFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, localFingerprint_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, remoteFingerprint_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, localFingerprint_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, remoteFingerprint_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code textsecure.CombinedFingerprint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_CombinedFingerprint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_CombinedFingerprint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.class, org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.Builder.class);
      }

      // Construct using org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocalFingerprintFieldBuilder();
          getRemoteFingerprintFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (localFingerprintBuilder_ == null) {
          localFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
        } else {
          localFingerprintBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (remoteFingerprintBuilder_ == null) {
          remoteFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
        } else {
          remoteFingerprintBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.internal_static_textsecure_CombinedFingerprint_descriptor;
      }

      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint getDefaultInstanceForType() {
        return org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.getDefaultInstance();
      }

      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint build() {
        org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint buildPartial() {
        org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint result = new org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (localFingerprintBuilder_ == null) {
          result.localFingerprint_ = localFingerprint_;
        } else {
          result.localFingerprint_ = localFingerprintBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (remoteFingerprintBuilder_ == null) {
          result.remoteFingerprint_ = remoteFingerprint_;
        } else {
          result.remoteFingerprint_ = remoteFingerprintBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint) {
          return mergeFrom((org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint other) {
        if (other == org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasLocalFingerprint()) {
          mergeLocalFingerprint(other.getLocalFingerprint());
        }
        if (other.hasRemoteFingerprint()) {
          mergeRemoteFingerprint(other.getRemoteFingerprint());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.whispersystems.libsignal.fingerprint.FingerprintProtos.CombinedFingerprint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 version = 1;
      private int version_ ;
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // optional .textsecure.FingerprintData localFingerprint = 2;
      private org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData localFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder> localFingerprintBuilder_;
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public boolean hasLocalFingerprint() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getLocalFingerprint() {
        if (localFingerprintBuilder_ == null) {
          return localFingerprint_;
        } else {
          return localFingerprintBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public Builder setLocalFingerprint(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData value) {
        if (localFingerprintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          localFingerprint_ = value;
          onChanged();
        } else {
          localFingerprintBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public Builder setLocalFingerprint(
          org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder builderForValue) {
        if (localFingerprintBuilder_ == null) {
          localFingerprint_ = builderForValue.build();
          onChanged();
        } else {
          localFingerprintBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public Builder mergeLocalFingerprint(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData value) {
        if (localFingerprintBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              localFingerprint_ != org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance()) {
            localFingerprint_ =
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.newBuilder(localFingerprint_).mergeFrom(value).buildPartial();
          } else {
            localFingerprint_ = value;
          }
          onChanged();
        } else {
          localFingerprintBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public Builder clearLocalFingerprint() {
        if (localFingerprintBuilder_ == null) {
          localFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
          onChanged();
        } else {
          localFingerprintBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder getLocalFingerprintBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLocalFingerprintFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder getLocalFingerprintOrBuilder() {
        if (localFingerprintBuilder_ != null) {
          return localFingerprintBuilder_.getMessageOrBuilder();
        } else {
          return localFingerprint_;
        }
      }
      /**
       * <code>optional .textsecure.FingerprintData localFingerprint = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder> 
          getLocalFingerprintFieldBuilder() {
        if (localFingerprintBuilder_ == null) {
          localFingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder>(
                  localFingerprint_,
                  getParentForChildren(),
                  isClean());
          localFingerprint_ = null;
        }
        return localFingerprintBuilder_;
      }

      // optional .textsecure.FingerprintData remoteFingerprint = 3;
      private org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData remoteFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder> remoteFingerprintBuilder_;
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public boolean hasRemoteFingerprint() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData getRemoteFingerprint() {
        if (remoteFingerprintBuilder_ == null) {
          return remoteFingerprint_;
        } else {
          return remoteFingerprintBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public Builder setRemoteFingerprint(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData value) {
        if (remoteFingerprintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          remoteFingerprint_ = value;
          onChanged();
        } else {
          remoteFingerprintBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public Builder setRemoteFingerprint(
          org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder builderForValue) {
        if (remoteFingerprintBuilder_ == null) {
          remoteFingerprint_ = builderForValue.build();
          onChanged();
        } else {
          remoteFingerprintBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public Builder mergeRemoteFingerprint(org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData value) {
        if (remoteFingerprintBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              remoteFingerprint_ != org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance()) {
            remoteFingerprint_ =
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.newBuilder(remoteFingerprint_).mergeFrom(value).buildPartial();
          } else {
            remoteFingerprint_ = value;
          }
          onChanged();
        } else {
          remoteFingerprintBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public Builder clearRemoteFingerprint() {
        if (remoteFingerprintBuilder_ == null) {
          remoteFingerprint_ = org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.getDefaultInstance();
          onChanged();
        } else {
          remoteFingerprintBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder getRemoteFingerprintBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRemoteFingerprintFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      public org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder getRemoteFingerprintOrBuilder() {
        if (remoteFingerprintBuilder_ != null) {
          return remoteFingerprintBuilder_.getMessageOrBuilder();
        } else {
          return remoteFingerprint_;
        }
      }
      /**
       * <code>optional .textsecure.FingerprintData remoteFingerprint = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder> 
          getRemoteFingerprintFieldBuilder() {
        if (remoteFingerprintBuilder_ == null) {
          remoteFingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintData.Builder, org.whispersystems.libsignal.fingerprint.FingerprintProtos.FingerprintDataOrBuilder>(
                  remoteFingerprint_,
                  getParentForChildren(),
                  isClean());
          remoteFingerprint_ = null;
        }
        return remoteFingerprintBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:textsecure.CombinedFingerprint)
    }

    static {
      defaultInstance = new CombinedFingerprint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:textsecure.CombinedFingerprint)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_textsecure_FingerprintData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_textsecure_FingerprintData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_textsecure_CombinedFingerprint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_textsecure_CombinedFingerprint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031FingerprintProtocol.proto\022\ntextsecure\"" +
      "8\n\017FingerprintData\022\021\n\tpublicKey\030\001 \001(\014\022\022\n" +
      "\nidentifier\030\002 \001(\014\"\225\001\n\023CombinedFingerprin" +
      "t\022\017\n\007version\030\001 \001(\r\0225\n\020localFingerprint\030\002" +
      " \001(\0132\033.textsecure.FingerprintData\0226\n\021rem" +
      "oteFingerprint\030\003 \001(\0132\033.textsecure.Finger" +
      "printDataB=\n(org.whispersystems.libsigna" +
      "l.fingerprintB\021FingerprintProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_textsecure_FingerprintData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_textsecure_FingerprintData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_textsecure_FingerprintData_descriptor,
              new java.lang.String[] { "PublicKey", "Identifier", });
          internal_static_textsecure_CombinedFingerprint_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_textsecure_CombinedFingerprint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_textsecure_CombinedFingerprint_descriptor,
              new java.lang.String[] { "Version", "LocalFingerprint", "RemoteFingerprint", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
